# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_auto_20180928_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
